name: my-drupal9-app
recipe: drupal9
config:
  webroot: web
  xdebug: debug
  config:
    php: .vscode/php.ini
env_file:
  - .env
services:
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  phpmyadmin:
    type: phpmyadmin